version: "3.7"

services:
  rust_ani:
      container_name: rust_ani
      build: .
      environment:
        - DATABASE_URL=${DATABASE_URL}
        - JWT_SECRET=${JWT_SECRET}
      ports:
        - '8090:8090'
        
  pg_db:
    image: postgres:15.1-alpine
    container_name: pg_db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root_pg
      - POSTGRES_DB=ani
    volumes:
      - db_pg_ani:/var/lib/postgresql/data/


  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - pg_db

volumes:
  db_pg_ani: