version: "3.7"

services:
  front_flutter:
    image: front_flutter:latest
    ports:
      - "80:80"
    restart: always
    container_name: front
    volumes:
      - ./.nginx:/etc/nginx/conf.d/default.conf

  rust_ani-rust_ani:
    image: rust_ani-rust_ani:latest
    container_name: rust_ani
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

        
  pg_db:
    image: postgres:15.1-alpine
    container_name: pg_db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root_pg
      - POSTGRES_DB=ani
    volumes:
      - db_pg_ani:/var/lib/postgresql/data/
    ports:
      - "5432:5432"


  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - pg_db

volumes:
  db_pg_ani: