//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

pub mod prelude;

pub mod bookmark;
pub mod episode;
pub mod history;
pub mod releases;
pub mod review;
pub mod user_friend_requests;
pub mod user_info;
pub mod users;
