//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

pub use super::bookmark::Entity as Bookmark;
pub use super::episode::Entity as Episode;
pub use super::history::Entity as History;
pub use super::releases::Entity as Releases;
pub use super::review::Entity as Review;
pub use super::user_friend_requests::Entity as UserFriendRequests;
pub use super::user_info::Entity as UserInfo;
pub use super::users::Entity as Users;
